# Generated by Django 4.0 on 2023-05-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория товара')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('oldprice', models.PositiveSmallIntegerField(verbose_name='Старая цена')),
                ('percent', models.PositiveSmallIntegerField(verbose_name='Скидка')),
                ('image', models.ImageField(upload_to='products/images', verbose_name='Фото')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('color', models.CharField(max_length=200, verbose_name='Цвет')),
                ('length_mm', models.PositiveSmallIntegerField(verbose_name='Длина')),
                ('width_mm', models.PositiveSmallIntegerField(verbose_name='Ширина')),
                ('height_mm', models.PositiveSmallIntegerField(verbose_name='Высота')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=200, verbose_name='Код товара')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('warranty_days', models.PositiveSmallIntegerField(verbose_name='Гарантия')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='В наличии')),
                ('leadtime', models.PositiveSmallIntegerField(verbose_name='Хз что это, уточнить у Темы')),
                ('availability', models.BooleanField(verbose_name='Доступно')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('material_secondary', models.CharField(max_length=200, verbose_name='Материал допольнительно')),
                ('color', models.CharField(max_length=200, verbose_name='Цвет')),
                ('base_material', models.CharField(max_length=200, verbose_name='Материал основания')),
                ('base_color', models.CharField(max_length=200, verbose_name='Цвет основания')),
                ('nearest_delivery_date', models.DateField(verbose_name='Ближайшая дата доставки')),
                ('service_life', models.PositiveSmallIntegerField(verbose_name='Срок службы')),
                ('country_of_origin', models.CharField(max_length=200, verbose_name='Страна производства')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_info', to='products.product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.vendor', verbose_name='Производитель'),
        ),
    ]
