# Generated by Django 4.0 on 2023-05-22 07:40

from django.db import migrations, models
import rating.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(validators=[rating.validators.validate_rating], verbose_name='Оценка пользователя'),
        ),
    ]
